source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.0.0'
gem 'jbuilder', '~> 1.0.1'
gem 'jquery-rails'
gem 'puma'
gem 'rails', '4.0.0.rc1'
gem 'redis'
gem 'sass-rails', '~> 4.0.0.rc1'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
